### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by AcoNCodes** [mailru/go-clickhouse#88] opened 2019-12-04 09:43 UTC
Hello, after the last commit I get this error:
github.com/mailru/go-clickhouse/conn.go:308:23: multiple-value uuid.NewV4() in single-value context

**Comment by DoubleDi** [comment] 2019-12-04 10:19
hello! Thanks for the issue. Will fix it in #87

**Comment by DoubleDi** [comment] 2019-12-04 10:55
it was a dependency version error. The issue is now fixed. please use 1.1.0 version in uuid package

**Comment by lexand** [comment] 2019-12-26 13:12
Is there a way to fix this (use 1.1.0 version in uuid package) but not use modules ?

**Comment by DoubleDi** [comment] 2019-12-26 13:39
you can use dep to get the correct versions of dependencies.
Here is the [Gopkg](https://github.com/mailru/go-clickhouse/blob/master/Gopkg.toml) file

**Closed** 2020-02-09 15:38 UTC
